### ISSUE TITLE
Trouble with Installation

### ISSUE THREAD

**Issue by ibeanubis** [twolven/mcp-stockscreen#1]
I cannot seem to get this running. I have all the prerequisites installed and all my other MCP servers run fine that I have setup, but this one I cannot seem to get to work. Any ideas on what could be going wrong? I really want to try this out!
<img width="581" alt="Screenshot 2024-12-22 at 1 58 28 PM" src="https://github.com/user-attachments/assets/1fc5b9bd-333d-4bda-86c5-c2dd4980aed1" />

**Comment by twolven** [comment]
This doesn't seem to be an issue with the stockscreen MCP server.  Stockscreen doesn't use any uv or uvx commands to run, it's pure python.

What do your logs located in your Claude folder show?
